language: c

env:
  matrix:
    - PACKAGES='g++ cmake make libqt4-dev' CMAKE=cmake
    - PACKAGES='mxe-i686-w64-mingw32.static-qt' CMAKE='cmake -DCMAKE_TOOLCHAIN_FILE=/usr/lib/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake'

install:
  - echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
  - sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  - sudo apt-get update
  - sudo apt-get install upx-ucl $PACKAGES

script:
  - $CMAKE . -Bbuild-dir
  - cmake --build build-dir --config Release

before_deploy:
  - upx -9 build-dir/battleship*

deploy:
  provider: releases
  api_key:
    secure: RAYIUKdy71W8RUy5BNvagr92dFJsaj3GK9zvcxr5qd1BoxJzXqVfuH7zgCg2+Ts9K4kxC03wkoLatCiQYFXcwkuppb7jVPOWDBAs0ba/FamzEvjgUNlKBRunXKGYhcMPANuN9M3HMk93SSeT/jT/QKTJeRJgbJY+KUdSFfok6Wo=
  file: "$(ls build-dir/battleship*)"
  skip_cleanup: true
  on:
    tags: true
