language: cpp

matrix:

  include:

    - env: BATTLESHIP_PLATFORM='linux64'
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc

    - env: BATTLESHIP_PLATFORM='windows32'
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc

    - env: BATTLESHIP_PLATFORM='windows64'
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc

    - env: BATTLESHIP_PLATFORM='macXX'
      os: osx
      osx_image: xcode7.2
      compiler: clang

before_install:
  - BATTLESHIP_TARGET="${BATTLESHIP_PLATFORM::${#BATTLESHIP_PLATFORM}-2}"
  - sudo apt-get update
  - ./build/${BATTLESHIP_TARGET}/requirements.sh

install:
  - source ./build/${BATTLESHIP_TARGET}/build.sh

script:
  - echo "Nothing."

before_deploy:
  - source build-dir/package.sh

deploy:
  provider: releases
  api_key: "$GH_API_KEY"
  file:
      - "$(ls battleship_*_${BATTLESHIP_PLATFORM}.exe)"
      - "$(ls battleship_*_*-portable.exe 2>/dev/null || echo build-dir/README.txt)"
  skip_cleanup: true
  on:
    tags: true
