language: cpp
sudo: required
dist: trusty # modern upx

env:
  matrix:
    - BATTLESHIP_TARGET=linux FILENAME_SUFFIX='linux64'
    - BATTLESHIP_TARGET=windows FILENAME_SUFFIX='windows32'
    - BATTLESHIP_TARGET=windows FILENAME_SUFFIX='windows64'

before_install:
  - sudo apt-get update
  - ./linux/requirements.sh
  - ./${BATTLESHIP_TARGET}/requirements.sh

install:
  - source ./${BATTLESHIP_TARGET}/build.sh

script:
  - echo "Nothing."

before_deploy:
  - strip $DEPLOY_FILE
  - upx -9 $DEPLOY_FILE
  - if [ -f "build-dir/wizard.nsi" ]; then
      source build-dir/nsis_wizard.sh;
    fi

deploy:
  provider: releases
  api_key: "$GH_API_KEY"
  file: "$(ls battleship_*_*.exe)"
  skip_cleanup: true
  on:
    tags: true
